__version__: 0.5.2
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.Resize
    always_apply: true
    height: 256
    interpolation: 1
    p: 1
    width: 256
  - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
    always_apply: false
    height: 224
    p: 1.0
    width: 224
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    always_apply: false
    max_pixel_value: 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    p: 1.0
    std:
    - 0.229
    - 0.224
    - 0.225
  - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
